import type { Metadata } from "next";
import { CourseDiagram } from "../../components/diagram";
export const metadata:Metadata={title:"Design system"};
const colors=[["Canvas","#0A0B09"],["Surface","#131512"],["Raised","#1A1D18"],["Ivory","#F3F0E6"],["Muted","#9C9D94"],["Signal","#D4FF32"],["Warning","#FF5A1F"],["Rule","#343730"]];
export default function DesignSystemPage(){return <div className="design-page page-pad"><header className="page-heading"><div><p className="eyebrow"><span>CLUB MANUAL · DARK SIGNAL</span><b>DS/01</b></p><h1>THE COURSE<br/>INSTRUMENT</h1><p>The interface behaves like a serious drum-machine manual: bold, blocky, high-contrast, information-dense, and calm enough for long lessons.</p></div></header>
  <section className="design-section"><div className="section-title"><span>01 · COLOR TOKENS</span><b>DARK FIELD + ACID SIGNAL</b></div><div className="swatch-grid">{colors.map(([name,value])=><article key={name} style={{background:value,color:["Ivory","Signal"].includes(name)?"#0A0B09":"#F3F0E6"}}><span>{name}</span><b>{value}</b></article>)}</div></section>
  <section className="design-section type-spec"><div className="section-title"><span>02 · TYPOGRAPHY</span><b>BLOCK + INSTRUCTION + DATA</b></div><div><article><span>DISPLAY · BARLOW CONDENSED 900</span><h2>RHYTHM IS<br/>A LIVING FIELD</h2></article><article><span>BODY · IBM PLEX SANS 400</span><p>Plain language establishes the mental model. Precise terminology names it. A musical example makes it audible. An operation turns it into action.</p></article><article><span>DATA · IBM PLEX MONO 500</span><code>1 e &amp; a · 2 e &amp; a · 3 e &amp; a · 4 e &amp; a</code></article></div></section>
  <section className="design-section"><div className="section-title"><span>03 · COMPONENT RULES</span><b>ONE PURPOSE PER SURFACE</b></div><div className="component-spec"><article className="ruled-card"><header><span>LESSON CARD</span><b>001</b></header><h3>STRUCTURE BEFORE DECORATION</h3><p>Hairline rules create hierarchy. Signal color indicates active progress. Orange is reserved for warnings or rhythmic exceptions.</p><footer>44PX MINIMUM TARGET</footer></article><article><button className="primary-cta">PRIMARY ACTION →</button><button className="secondary-button">SECONDARY ACTION</button><p>Motion is fast and mechanical: 140ms micro, 220ms state, 320ms page reveal.</p></article></div></section>
  <section className="design-section"><div className="section-title"><span>04 · EDUCATIONAL IMAGERY</span><b>DIAGRAMS, NOT DECORATION</b></div><p className="design-copy">The course does not need generic studio photographs or unlicensed artist portraits. Its visual language is code-native and explanatory: step grids, meter orbits, envelopes, signal paths, machine-affordance plates, modulation networks, spectra, and arrangement-energy maps. Each appears only where it materially clarifies a relationship.</p><div className="diagram-samples"><CourseDiagram kind="four-four"/><CourseDiagram kind="machines"/><CourseDiagram kind="energy"/></div></section>
  <section className="design-section token-table"><div className="section-title"><span>05 · CORE VARIABLES</span><b>IMPLEMENTATION CONTRACT</b></div><table><thead><tr><th>FAMILY</th><th>TOKENS</th><th>RULE</th></tr></thead><tbody><tr><td>Spacing</td><td>4 · 8 · 12 · 16 · 24 · 32 · 48 · 64 · 96</td><td>Dense information; generous section separation.</td></tr><tr><td>Radius</td><td>0 · 2 · 4px</td><td>Nearly square. Never soft consumer-app bubbles.</td></tr><tr><td>Motion</td><td>140 · 220 · 320ms</td><td>No glow, bounce, or decorative pulsing.</td></tr><tr><td>Focus</td><td>3px signal + 2px canvas offset</td><td>Always visible; never color alone.</td></tr><tr><td>Persistence</td><td>localStorage + JSON export</td><td>Private by default and portable by choice.</td></tr></tbody></table></section>
</div>}
