import { lessons, type Lesson } from "./course";

export type SkillDomain = "Rhythm"|"Sound design"|"Systems"|"Composition"|"Engineering";
export interface SkillDefinition {
  id:string;name:string;domain:SkillDomain;description:string;why:string;evidence:string;
  prerequisites:string[];keywords:string[];
}

export const skills:SkillDefinition[]=[
  {id:"meter-pulse",name:"Meter and pulse",domain:"Rhythm",description:"Feel 4/4 as a hierarchy of arrival, answer, renewal, and preparation—not merely four kick positions.",why:"Every syncopation, omission, and groove decision depends on a pulse the listener can predict.",evidence:"Carry the count through a kickless phrase and restore the kick on the intended beat 1.",prerequisites:[],keywords:["4/4","meter","pulse","four beats","downbeat","backbeat"]},
  {id:"subdivision-counting",name:"Subdivision and counting",domain:"Rhythm",description:"Locate eighths, sixteenths, triplets, and pickups inside the beat by ear, voice, and body.",why:"Subdivisions give rhythmic ideas precise addresses without turning the grid into a commandment.",evidence:"Count 1-e-&-a while tapping a separate accent pattern without losing the quarter-note floor.",prerequisites:["meter-pulse"],keywords:["subdivision","counting","1 e & a","triplet","offbeat"]},
  {id:"onset-architecture",name:"Onset architecture",domain:"Rhythm",description:"Design a phrase by deciding where events begin before sound choice or effects obscure the pattern.",why:"Clear placement lets you diagnose whether a groove problem belongs to rhythm, accent, decay, or timbre.",evidence:"Create several distinct dry gaits from one kit and explain each event as anchor, lift, pickup, or answer.",prerequisites:["meter-pulse","subdivision-counting"],keywords:["onset architecture","grid","pattern","skeleton","anchor, lift"]},
  {id:"accent-velocity",name:"Accent and velocity",domain:"Rhythm",description:"Create structural, secondary, and ghost events through controlled emphasis.",why:"A pattern with equal stress is like speech with every syllable shouted at the same volume.",evidence:"Produce three clearly different feels without moving a MIDI note, then identify their accent hierarchies blind.",prerequisites:["onset-architecture"],keywords:["velocity","accent","ghost note","stress"]},
  {id:"decay-articulation",name:"Decay and articulation",domain:"Rhythm",description:"Shape how long each event occupies time and how much negative space remains for the next event.",why:"Duration is rhythm: a tail can connect, mask, push, or choke later subdivisions.",evidence:"Reveal a hidden ghost note or change the gait by editing decay alone.",prerequisites:["onset-architecture"],keywords:["decay","articulation","transient, body","tail","choke"]},
  {id:"swing-microtiming",name:"Swing and microtiming",domain:"Rhythm",description:"Use systematic timing relationships to create lean, shuffle, bounce, and drag while preserving a stable floor.",why:"Repeated deviation becomes handwriting; unrelated deviation becomes instability.",evidence:"Choose and defend a tops-only groove, then distinguish straight, swung, and randomly loose versions blind.",prerequisites:["subdivision-counting","onset-architecture"],keywords:["swing","microtiming","groove pool","shuffle","groove comparison"]},
  {id:"embodied-timing",name:"Embodied timing",domain:"Rhythm",description:"Connect pad performance, limb coordination, velocity, and intentional quantization to the programmed grid.",why:"Your hands expose timing relationships and coordination limits that a mouse can hide.",evidence:"Record, partially correct, and reproduce a pad performance while preserving its expressive feature.",prerequisites:["meter-pulse","swing-microtiming"],keywords:["finger-drumming","embodied","pad feel","performance ladder","hands"]},
  {id:"rhythmic-dialects",name:"Rhythmic dialects",domain:"Rhythm",description:"Translate house, techno, dub, hardgroove, microhouse, UK garage, and Latin-derived cells through movement logic.",why:"Genre becomes transferable when understood as timing, density, accent, envelope, and space—not sample-pack labels.",evidence:"Render one invariant skeleton as four audibly distinct gaits and name each version’s main motion source.",prerequisites:["accent-velocity","decay-articulation","swing-microtiming"],keywords:["dialect","house","hardgroove","dembow","clave","raptor","microhouse","2-step"]},
  {id:"low-end-design",name:"Kick and low-end design",domain:"Sound design",description:"Separate impact, sustained weight, pitch, and atmospheric pressure in time and frequency.",why:"Low-end authority comes from role assignment and headroom, not from making every component enormous.",evidence:"Make kick, bass, or rumble alternate perceptually while remaining clear in mono at several levels.",prerequisites:["decay-articulation","signal-flow"],keywords:["kick, bass","low-end","rumble","sub/bass","gravity management"]},
  {id:"percussive-synthesis",name:"Percussive synthesis",domain:"Sound design",description:"Build foreground identities with transient shape, limited pitch, evolving material, and rhythmic space.",why:"A techno lead can behave like a drum wearing a synth mask instead of a conventional melody.",evidence:"Create a one- or two-pitch object that holds attention for 64 bars without becoming a pad or generic stab.",prerequisites:["envelopes-filters","fm-resonance"],keywords:["percussive synthesis","percussive synth","lead that refuses","noise burst"]},
  {id:"envelopes-filters",name:"Envelopes and filtering",domain:"Sound design",description:"Turn continuous sources into gestures and carve spectral space with time-varying amplitude, pitch, and filter shapes.",why:"The envelope is the drawn force that makes a source strike, breathe, swell, or disappear.",evidence:"Predict which envelope or filter control fixes a sound that is too soft, boomy, smeared, or bright.",prerequisites:["decay-articulation"],keywords:["envelope is","subtractive synthesis","filter envelope","pitch envelope","amplitude envelope"]},
  {id:"fm-resonance",name:"FM, resonance, and material",domain:"Sound design",description:"Create metallic, tubular, woody, glassy, or unstable spectra through frequency relationships and ringing systems.",why:"These mechanisms generate the percussive, non-stabby foreground materials central to the target aesthetic.",evidence:"Build distinct material families while keeping pitch and level behavior controlled.",prerequisites:["envelopes-filters"],keywords:["fm synthesis","resonator","comb","feedback and resonant","fm index"]},
  {id:"sampling-granular",name:"Sampling and granular transformation",domain:"Sound design",description:"Treat sample start, playback position, slicing, grains, field recording, and resampling as compositional variables.",why:"Recorded material can become rhythm, place, memory, or a new instrument rather than static decoration.",evidence:"Derive several functional roles from one recording while preserving a coherent source identity.",prerequisites:["envelopes-filters"],keywords:["sample synthesis","granular","field recording","place becomes","sampling"]},
  {id:"space-delay",name:"Space and delay rhythm",domain:"Sound design",description:"Design depth with filtered rooms, delays, reverbs, direct/wet ratios, and timed memory.",why:"Space occupies future rhythmic territory and can answer a dry event like another player.",evidence:"Make a return supply a meaningful rhythmic role without obscuring the seed, kick, or low end.",prerequisites:["signal-flow","decay-articulation"],keywords:["return tracks","dub delay","space becoming","delay","reverb"]},
  {id:"distortion-feedback",name:"Distortion, feedback, and resampling",domain:"Sound design",description:"Use nonlinear color and feedback within safe ranges, then print useful uncertainty into editable audio.",why:"Commitment converts unstable systems into material you can arrange, compare, and reuse.",evidence:"Level-match a processed chain, control its peak state, and extract a better resample than the live source.",prerequisites:["signal-flow","space-delay"],keywords:["distortion","feedback","resampling","parallel dirt","nonlinear"]},
  {id:"signal-flow",name:"Signal flow and gain",domain:"Engineering",description:"Follow audio and control data from source through devices, sends, groups, returns, and recording destinations.",why:"Complex workflows become small, testable boundaries when you can say where the signal should be at every stage.",evidence:"Diagnose a silent or unexpectedly loud chain by verifying one boundary at a time.",prerequisites:[],keywords:["signal flow","gain staging","follow the water","routing diagnosis","amplitude, gain"]},
  {id:"monitoring-mix",name:"Monitoring and moving-system mix",domain:"Engineering",description:"Judge hierarchy, masking, mono compatibility, peaks, and translation across the system’s quietest and busiest states.",why:"A mix that works only in one automation state is not a finished moving system.",evidence:"Pass quiet, loud, mono, and second-system checks without losing kick, hierarchy, or motion.",prerequisites:["signal-flow","low-end-design"],keywords:["monitoring","mixing moving","mono compatibility","masking","mix-state"]},
  {id:"modulation-design",name:"Modulation design",domain:"Systems",description:"Assign base, range, rate, phase, and musical function to bounded sources of ongoing movement.",why:"Aliveness comes from coordinated tendencies; random movement without identity is only instability.",evidence:"Build sub-bar, phrase, and long-cycle motion whose contributions can be heard and explained separately.",prerequisites:["signal-flow","envelopes-filters"],keywords:["modulation","morphing systems","lfo","envelope follower","motion budget"]},
  {id:"macro-performance",name:"Macros and performance states",domain:"Systems",description:"Map many internal parameters into a few safe, semantic directions with neutral, working, edge, and reset states.",why:"A macro is a playable musical control, not merely several knobs attached to one knob.",evidence:"Perform a build, withdrawal, and reset without unsafe jumps or losing the sound’s identity.",prerequisites:["modulation-design"],keywords:["macro","big knob","performance passes","macro control","variations"]},
  {id:"generative-systems",name:"Generative rhythm and probability",domain:"Systems",description:"Use unequal cycles, chance, conditions, and generators to propose material while retaining selection and authorship.",why:"A generator can discover relationships, but it cannot decide which events serve the track.",evidence:"Capture, edit, and explain a generated pattern whose retained events form an intelligible conversation.",prerequisites:["onset-architecture","modulation-design"],keywords:["controlled randomness","generative","probability","chance","unequal cycles"]},
  {id:"ableton-workflow",name:"Ableton workflow",domain:"Systems",description:"Use Live as the arrangement, modulation, resampling, and state-management home for the course.",why:"A stable mothership prevents software friction from fragmenting musical attention.",evidence:"Open the template and move from source to routed, modulated, printed material without rebuilding infrastructure.",prerequisites:["signal-flow"],keywords:["ableton operations","ableton template","groove pool workflow","clip envelopes","follow actions"]},
  {id:"maschine-integration",name:"Maschine integration",domain:"Systems",description:"Give pads, Step mode, sampling, and routed audio clear jobs inside an Ableton-centered system.",why:"Two sequencers help only when each owns a defined stage and the handoff is testable.",evidence:"Reopen the routing template, trigger and print the intended sound, and state what stays editable in each host.",prerequisites:["signal-flow","ableton-workflow","embodied-timing"],keywords:["maschine","machine mindsets","pad-sampler","step mode"]},
  {id:"reference-listening",name:"Reference listening and translation",domain:"Composition",description:"Analyze one audible variable, a complete system, or full form without guessing hidden equipment.",why:"References teach mechanisms when you separate evidence from imitation and translate the relationship into your own material.",evidence:"Produce a reference map and an original study that preserves function while changing source identity.",prerequisites:["meter-pulse","signal-flow"],keywords:["reference","artist-axis","listening","reconstruction","aesthetic north star"]},
  {id:"tonal-gravity",name:"Tonal gravity without over-writing",domain:"Composition",description:"Manage pitch centers, intervals, resonance, chord color, and ambiguity without requiring conventional melody.",why:"Minimal techno still has tonal attraction; uncontrolled resonances can conflict even when no melody is intended.",evidence:"Complete one- and two-note studies whose interest comes from rhythm, register, and timbre motion.",prerequisites:["fm-resonance","low-end-design"],keywords:["tonality","pitch as gravity","two-pitch","harmony","chord"]},
  {id:"arrangement-form",name:"Arrangement and transitions",domain:"Composition",description:"Choreograph attention through density, spectrum, continuity, weight, instability, subtraction, and return.",why:"A track develops by changing the listener’s model of existing material—not by adding a new instrument whenever attention fades.",evidence:"Turn one loop into a coherent multi-minute form and explain every major boundary through energy axes.",prerequisites:["onset-architecture","macro-performance"],keywords:["arrangement","transition grammar","energy axes","attention choreography","six-minute"]},
  {id:"finishing-assessment",name:"Finishing and self-assessment",domain:"Composition",description:"Use acceptance criteria, rubrics, evidence, exports, and limited revision rounds to complete work deliberately.",why:"Finishing, diagnosing, and choosing what to repeat are separate skills from generating ideas.",evidence:"Export a track, score it against the rubric, complete a postmortem, and define the next targeted study.",prerequisites:["arrangement-form","monitoring-mix","reference-listening"],keywords:["assessment","rubric","finish","capstone","completion checklist","diagnostic"]},
];

function scoreSkill(lesson:Lesson,skill:SkillDefinition){
  const title=lesson.title.toLowerCase(),part=lesson.part.toLowerCase(),intro=lesson.markdown.slice(0,1800).toLowerCase();
  return skill.keywords.reduce((score,keyword)=>{const key=keyword.toLowerCase();return score+(title.includes(key)?5:0)+(part.includes(key)?2:0)+(lesson.concepts.some(c=>c.toLowerCase()===key)?3:0)+(intro.includes(key)?1:0);},0);
}

export function getSkillsForLesson(lesson:Lesson,limit=5){
  const ranked=skills.map(skill=>({skill,score:scoreSkill(lesson,skill)})).filter(item=>item.score>0).sort((a,b)=>b.score-a.score);
  if(ranked.length)return ranked.slice(0,limit).map(item=>item.skill);
  const fallback:Record<string,string>={rhythm:"onset-architecture",sound:"envelopes-filters",systems:"modulation-design",arrangement:"arrangement-form",practice:"finishing-assessment",reference:"reference-listening",foundation:"signal-flow"};
  return [skills.find(skill=>skill.id===fallback[lesson.kind])!];
}

export const lessonSkillMap:Record<string,string[]>=Object.fromEntries(lessons.map(lesson=>[lesson.id,getSkillsForLesson(lesson).map(skill=>skill.id)]));
export const skillLessonMap:Record<string,string[]>=Object.fromEntries(skills.map(skill=>[skill.id,lessons.filter(lesson=>lessonSkillMap[lesson.id].includes(skill.id)).map(lesson=>lesson.id)]));
export const skillById=(id:string)=>skills.find(skill=>skill.id===id);
