import fs from "node:fs";
import path from "node:path";
import { marked } from "marked";

const root=process.cwd();
const source=fs.readFileSync(path.join(root,"content/living-techno-curriculum.md"),"utf8");
const slugify=value=>value.normalize("NFKD").replace(/[–—]/g,"-").replace(/[^a-zA-Z0-9]+/g,"-").replace(/^-|-$/g,"").toLowerCase().slice(0,72);
const plain=value=>value.replace(/```[\s\S]*?```/g," ").replace(/https?:\/\/\S+/g," ").replace(/[*_`>#|\[\]()]/g," ").replace(/\s+/g," ").trim();
const descriptionFrom=markdown=>{const blocks=markdown.split(/\n\s*\n/).map(plain).filter(item=>item.length>50&&!item.startsWith("Change Rationale"));const value=blocks[0]||"A guided lesson in rhythm, sound, and living electronic systems.";return value.length>190?`${value.slice(0,187).trim()}…`:value;};
const lessonKind=(title,part)=>{const h=`${title} ${part}`.toLowerCase();if(/reference|artist|resource|genre|dialect/.test(h))return"reference";if(/sound|synth|filter|fm|wavetable|granular|spectrum|envelope/.test(h))return"sound";if(/arrang|transition|performance|mix|export|capstone/.test(h))return"arrangement";if(/modulat|macro|system|random|generative|routing|maschine|ableton/.test(h))return"systems";if(/rhythm|grid|groove|timing|4\/4|beat|percussion|kick|hat|clave/.test(h))return"rhythm";if(/exercise|diagnostic|practice|assessment|week/.test(h))return"practice";return"foundation";};
const diagramKind=(title,markdown)=>{const h=`${title} ${markdown.slice(0,1200)}`.toLowerCase();if(/4\/4|four beats|meter|grid is a dance floor/.test(h))return"four-four";if(/signal flow|routing|follow the water/.test(h))return"signal-flow";if(/envelope|transient, body|decay/.test(h))return"envelope";if(/machine|step sequencer|pattern/.test(h))return"machines";if(/energy axes|arrangement grammar|transition/.test(h))return"energy";if(/modulation|macro|morph|random/.test(h))return"modulation";if(/frequency|spectrum|filter/.test(h))return"spectrum";if(/rhythm|groove|subdivision/.test(h))return"step-grid";return null;};
const conceptTags=(markdown,title)=>{const text=`${title} ${markdown}`.toLowerCase();return["4/4","accent","arrangement","automation","decay","envelope","feedback","groove","macro","meter","microtiming","modulation","percussion","probability","resampling","rhythm","signal flow","spectrum","swing","syncopation","timbre","velocity"].filter(term=>text.includes(term.toLowerCase())).slice(0,6);};
function addHeadingAnchors(html){const headings=[];const anchored=html.replace(/<h([23])>(.*?)<\/h\1>/g,(_m,level,inner)=>{const label=plain(inner);const base=slugify(label)||"section";let id=base,suffix=2;while(headings.some(h=>h.id===id))id=`${base}-${suffix++}`;headings.push({id,label});const exercise=/^(exercise|lab|recipe|study|workflow|day|card)/i.test(label);return`<h${level} id="${id}"${exercise?' data-section="exercise"':""}>${inner}</h${level}>`;});return{html:anchored,headings};}
function renderMarkdown(markdown,glossaryTerms){
  let html=marked.parse(markdown,{gfm:true,breaks:false});
  html=html.replace(/<(\/?)h([3-6])([^>]*)>/g,(_match,slash,level,rest)=>`<${slash}h${Number(level)-1}${rest}>`);
  html=html.replace(/<a href="(https?:\/\/[^\"]+)"/g,'<a class="external-link" href="$1" target="_blank" rel="noreferrer"');
  html=html.replace(/<p><strong>(Purpose|Why|Listen for|Common failure(?:s)?|Pass condition|Deliverable|Starting state|Setup|Action|Procedure|Constraints|Hint(?: [^<:]*)?):<\/strong>\s*([\s\S]*?)<\/p>/gi,'<aside class="learning-callout"><strong>$1</strong><span>$2</span></aside>');
  html=html.replace(/<table>/g,'<div class="table-region" role="region" aria-label="Scrollable lesson table" tabindex="0"><table>').replace(/<\/table>/g,'</table></div>');
  for(const term of glossaryTerms){const escaped=term.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const target=`/glossary/?q=${encodeURIComponent(term)}`;html=html.replace(new RegExp(`<strong>${escaped}:</strong>`,`gi`),`<a class="term-link" href="${target}"><strong>${term}</strong></a>:`).replace(new RegExp(`<strong>${escaped}</strong>`,`gi`),`<a class="term-link" href="${target}"><strong>${term}</strong></a>`);}
  return addHeadingAnchors(html);
}
function parse(){const lines=source.split("\n"),drafts=[],synthetic=[];let part="Start here",active=null,h1Active=null;const push=()=>{if(active&&plain(active.lines.join("\n")).length>30)drafts.push(active);};const pushH1=()=>{if(h1Active&&plain(h1Active.lines.join("\n")).length>30)synthetic.push(h1Active);h1Active=null;};for(const line of lines){const h1=line.match(/^#\s+(.+)/),h2=line.match(/^##\s+(.+)/);if(h1&&!h2){push();pushH1();active=null;part=h1[1].startsWith("Living Techno")?"Start here":h1[1];const title=h1[1].startsWith("Living Techno")?"Course overview":h1[1].replace(/^Appendix [A-Z] —\s*/,"");h1Active={title,part,lines:[]};continue}if(h2){pushH1();push();active={title:h2[1],part,lines:[]};continue}if(active)active.lines.push(line);else if(h1Active)h1Active.lines.push(line)}push();pushH1();drafts.push(...synthetic);const glossaryDraft=drafts.find(draft=>draft.title.toLowerCase()==="glossary");const glossaryTerms=(glossaryDraft?glossaryDraft.lines:[]).map(line=>line.match(/^- \*\*(.+?):\*\*/)?.[1]).filter(Boolean).sort((a,b)=>b.length-a.length);return drafts.map((draft,index)=>{const markdown=draft.lines.join("\n").trim(),rendered=renderMarkdown(markdown,glossaryTerms),sequence=index+1,slug=`${String(sequence).padStart(3,"0")}-${slugify(draft.title)}`,wordCount=plain(markdown).split(/\s+/).filter(Boolean).length;return{id:slug,slug,sequence,title:draft.title,part:draft.part,partSlug:slugify(draft.part),kind:lessonKind(draft.title,draft.part),diagram:diagramKind(draft.title,markdown),description:descriptionFrom(markdown),markdown,html:rendered.html,wordCount,minutes:Math.max(3,Math.ceil(wordCount/190)),headings:rendered.headings,concepts:conceptTags(markdown,draft.title)};});}
const lessons=parse();
fs.mkdirSync(path.join(root,"data"),{recursive:true});
fs.writeFileSync(path.join(root,"data/course.json"),JSON.stringify(lessons));
console.log(`Generated ${lessons.length} course lessons.`);
